# More details on how to configure the Travis build
# http://docs.travis-ci.com/user/build-configuration/

# Enabling container based infrastructure hoping it will help the build speed
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/

sudo: true 
language: java
jdk:
        - oraclejdk7
        - openjdk7
 
before_install:
        - chmod +x gradlew
        - chmod +x ./Server/createDB
        - ./Server/createDB
script:
        - cd Server/
        - sudo ../gradlew assemble
        - sudo ../gradlew check
        - java -jar build/libs/Server-all-0.1.jar 
